Rails.application.config.assets.precompile += %w( notice.png )
Rails.application.config.assets.precompile += %w( welcome.css )
Rails.application.config.assets.precompile += %w( workspace.css )
Rails.application.config.assets.precompile += %w( ie-spacer.gif )
Rails.application.config.assets.precompile += %w( gritter.png)
Rails.application.config.assets.precompile += %w( gritter-close.png)