development:
  host: localhost
  username: root
  password: root
  adapter: postgresql
  encoding: utf8
  database: love_letter_mashup_development
  pool: 5

test:
  host: localhost
  username: root
  password: root
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: love_letter_mashup_test
  pool: 5

production: 
  host: localhost
  username: root
  password: root
  adapter: postgresql
  encoding: utf8
  database: love_letter_mashup
  pool: 5