development:

  adapter: postgresql
  encoding: utf8
  database: love_letter_mashup_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: love_letter_mashup_test
  pool: 5

production:  
  adapter: postgresql
  encoding: utf8
  database: love_letter_mashup
  pool: 5