# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d35c8eb35874f8e2288399f61ee629825024222566938fdbdb6209741e7b31343cd40ba64e0b1206b3098b50df6b015e6153f13b9b1471b582eabb0826d47500
  facebook_id:
  facebook_secret:
  twitter_key: SOgJoziLVerHqumXGpTY6rtOa
  twitter_secret: 4eDXKqtXc2Hq2IbbP02x6YiPfuyAqIkEJycTLPDXOXfPUsH1Nh
  twitter_token: 240692635-5kCkciANSZilba3sqpg62z42XAth8mDAMsMHdwyR
  twitter_token_secret: f6cp6wEq5lCnXl0GXvy94MVLZrdXe86sMkddmV2rvETn3
  facebook_id: 515475628578429
  facebook_secret: 8c581dd17b7e70eaa744a6c1424744be

test:
  secret_key_base: 455a4a1d308773e5a786dc956fd889592c70a83596f12c890c7ddc0c2adc43b9592b068f037cfcb2d170af993e22776c40eeed33c6562c94f7a36fd5d0db174b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
